name: Deploy to VPS

on:
  push:
    branches: [main, test-server] # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        

      - name: Deploy to VPS via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2025
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            chmod -R 775 storage bootstrap/cache
            
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force --database=mysql
            php artisan app:migrate-tenants
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            

            
      - name: Deploy to VPS 2 via SSH KEY
        if: github.ref == 'refs/heads/test-server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.SERVER2_USERNAME }}
          key: ${{ secrets.SERVER2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT2_PATH }}

            chmod -R 775 storage bootstrap/cache
            
            git pull origin test-sever
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force --database=mysql
            php artisan app:migrate-tenants
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache